FROM python:3.11-slim AS build

RUN pip install --no-cache-dir poetry==2.1.3 poetry-plugin-export==1.9.0

WORKDIR /build

COPY pyproject.toml poetry.lock ./

RUN poetry export --with dev --format requirements.txt --output requirements.txt

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir -r requirements.txt


FROM python:3.11-slim

COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app
